# Generated by Django 5.0.6 on 2024-06-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Complain Type',
            },
        ),
        migrations.CreateModel(
            name='UserComplains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bully_name', models.CharField(default='Unknown', max_length=50)),
                ('bully_id', models.CharField(blank=True, max_length=30, null=True)),
                ('bully_picture', models.ImageField(blank=True, null=True, upload_to='bully_pictures/')),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('complain_description', models.TextField(max_length=1000)),
                ('complain_validation', models.BooleanField(default=False)),
                ('complain_status', models.CharField(default='Processing', max_length=30)),
                ('proctor_decision', models.CharField(blank=True, max_length=1000, null=True)),
                ('guilty', models.BooleanField(blank=True, default=False, null=True)),
                ('complain_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.complain_types')),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinformations')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationdata')),
            ],
            options={
                'verbose_name': 'User Complains',
            },
        ),
        migrations.CreateModel(
            name='UserComplainProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='complain_proofs/<django.db.models.fields.related.ForeignKey>/')),
                ('proof_image_to_text', models.CharField(blank=True, max_length=400, null=True)),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.usercomplains')),
            ],
            options={
                'verbose_name': 'Complain Proves',
            },
        ),
    ]
