# Generated by Django 5.0.6 on 2024-06-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplains',
            name='bully_picture',
        ),
        migrations.CreateModel(
            name='BullyPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bully_image', models.ImageField(blank=True, null=True, upload_to='bully_image/<django.db.models.fields.related.ForeignKey>/')),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.usercomplains')),
            ],
            options={
                'verbose_name': 'Bully Images',
            },
        ),
    ]
