# Generated by Django 5.0.6 on 2024-06-19 06:21

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_usercomplains_bully_picture_bullypictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullypictures',
            name='bully_image',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.bully_image_upload_to),
        ),
        migrations.AlterField(
            model_name='usercomplainproof',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.prove_image_upload_to),
        ),
    ]
