# Generated by Django 5.0.6 on 2024-06-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_bullypictures_bully_image_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.CharField(max_length=300)),
                ('is_seen', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinformations')),
            ],
            options={
                'verbose_name': 'User Notifications',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.DateTimeField()),
                ('meeting_message', models.CharField(max_length=1000)),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.usercomplains')),
            ],
            options={
                'verbose_name': 'Scheduled Meetings',
            },
        ),
    ]
