# Generated by Django 5.0.6 on 2024-06-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_notifications_scheduledmeetings'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeetings',
            name='user_id',
            field=models.ForeignKey(default=2020202, on_delete=django.db.models.deletion.CASCADE, to='user.userinformations'),
            preserve_default=False,
        ),
    ]
