# Generated by Django 5.0.6 on 2024-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_scheduledmeetings_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplains',
            name='is_meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
