# Generated by Django 5.0.6 on 2024-07-15 11:35

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_usercomplains_is_meeting_scheduled'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100, verbose_name=django.db.models.fields.CharField)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinformations')),
            ],
            options={
                'verbose_name': 'Chatbot Threads',
            },
        ),
    ]
