# Generated by Django 5.0.6 on 2024-07-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_chatbotthreads'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotthreads',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userinformations'),
        ),
    ]
