# Generated by Django 5.0.6 on 2024-07-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_schedulerrecords_execution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainProofExtractedStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_strings', models.TextField(blank=True, null=True)),
                ('prediction_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.usercomplainproof')),
            ],
            options={
                'verbose_name': 'Extracted Texts From Images',
            },
        ),
    ]
