# Generated by Django 5.0.6 on 2024-07-27 18:56

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_schedulerrecords_complain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplainproof',
            name='processed_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.prove_processed_image_upload_to),
        ),
    ]
