# Generated by Django 5.0.6 on 2024-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_usercomplainproof_processed_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainproofextractedstrings',
            name='bbox',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
