# Generated by Django 5.0.6 on 2024-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_complainproofextractedstrings_bbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainproofextractedstrings',
            name='cyberBullyingFlag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
