# Generated by Django 5.0.6 on 2024-07-31 10:38

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_complainproofextractedstrings_cyberbullyingflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplainproof',
            name='cyber_bullying_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomplainproof',
            name='cyber_bullying_flag_picture',
            field=models.ImageField(blank=True, null=True, upload_to=system.models.prove_cyberbullying_flagged_picture),
        ),
    ]
