# Generated by Django 5.0.6 on 2024-07-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_usercomplainproof_cyber_bullying_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomplains',
            old_name='complain_validation',
            new_name='complain_cyberBullying_flag_validation',
        ),
    ]
