# Generated by Django 5.0.6 on 2024-06-15 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('user_picture', models.ImageField(blank=True, default='user_pictures/default_picture.png', null=True, upload_to='user_pictures/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_proctor', models.BooleanField(default=False)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationdata')),
            ],
            options={
                'verbose_name': 'Registered User Information',
            },
        ),
    ]
